aijTder – Fortran Program
aijTder Subroutine
MIT
26 statements
Source File
public subroutine aijTder(T, aij, daijdT, daij2dT2)
Uses
mixture
mixing_rules
Calculate the binary atractive term matrix
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: T
Temperature
real(kind=wp), intent(out) :: aij(nc,nc)
Atractive binary terms matrix
real(kind=wp), intent(out) :: daijdT(nc,nc)
Atractive binary terms matrix first derivative with temperature
real(kind=wp), intent(out) :: daij2dT2(nc,nc)
Atractive binary terms matrix second derivative with temperature
Calls
Called by
Contents
None
Call graph
aijtder calls atder, kij_tdep, quadtratic
amixtnder calls aijtder
helmholtz_energy calls amixtnder