aTder – Fortran Program
aTder Subroutine
MIT
18 statements
Source File
public subroutine aTder(T, a, dadT, dadT2)
Uses
mixture
Calculate the atractive parameter at T temperature. the subroutine will read the mixture's model and based on that will use the corresponding rule.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: T
Temperature
real(kind=wp), intent(out) :: a(nc)
Atractive parameter at T
real(kind=wp), intent(out) :: dadT(nc)
First deritvative with T
real(kind=wp), intent(out) :: dadT2(nc)
Second derivative with T
Called by
Contents
None
Call graph
aijtder calls atder
amixtnder calls aijtder
helmholtz_energy calls amixtnder