get_Zc_OMa_OMb – Fortran Program
get_Zc_OMa_OMb Subroutine
MIT
12 statements
Source File
public subroutine get_Zc_OMa_OMb(del1, Zc, OMa, OMb)
Arguments
Type Intent Optional Attributes Name
real(kind=8), intent(in) :: del1
real(kind=8), intent(out) :: Zc
real(kind=8), intent(out) :: OMa
real(kind=8), intent(out) :: OMb
Called by
Contents
None
Call graph
rkpr_critical_from_params calls get_zc_oma_omb
rkpr_params_from_crit calls get_zc_oma_omb
srk_params_from_crit calls get_zc_oma_omb
pr_params_from_crit calls get_zc_oma_omb
srk_critical_from_params calls get_zc_oma_omb
pr_critical_from_params calls get_zc_oma_omb