rkpr_params_from_crit – Fortran Program
rkpr_params_from_crit Subroutine
MIT
93 statements
Source File
public subroutine rkpr_params_from_crit(Tc, Pc, w, R, ac, b, k, del1, Vceos, T, Pvdat, RhoLsat)
Get the RKPR EOS parameters from the substance critical properties.
Arguments
Type Intent Optional Attributes Name
real(kind=8), intent(in) :: Tc
Critical temperature
real(kind=8), intent(in) :: Pc
Critical pressure
real(kind=8), intent(in) :: w
accentric factor
real(kind=8), intent(in) :: R
Gas constant
real(kind=8), intent(out) :: ac
ac parameter
real(kind=8), intent(out) :: b
covolume
real(kind=8), intent(out) :: k
k to calculate "a" with ac and T
real(kind=8), intent(inout), optional :: del1
delta_1
real(kind=8), intent(inout), optional :: Vceos
Critical volume at specification
real(kind=8), intent(in), optional :: T
Temperature used to either estimate k or del1
real(kind=8), intent(inout), optional :: Pvdat
Vapor pressure used to estimate k
real(kind=8), intent(in), optional :: RhoLsat
Saturation density used to estimate del1
Calls
Contents
None
Call graph
rkpr_params_from_crit calls vaporpressure, d, getdel1, get_zc_oma_omb
vaporpressure calls vaporpressure, vcalc, fug_calc
vcalc calls vcalc, vdwg_derivs
fug_calc calls vdwg_derivs