VCALC – Multicomponent Equations of State
VCALC Subroutine
MIT
49 statements
Source File
public recursive subroutine VCALC(ITYP, a, b, del1, T, P, V)
Uses
constants
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ITYP
real(kind=8), intent(in) :: a
real(kind=8), intent(in) :: b
real(kind=8), intent(in) :: del1
real(kind=8), intent(in) :: T
real(kind=8), intent(in) :: P
real(kind=8), intent(out) :: V
Calls
Called by
Contents
Variables
AT AVAP DER F FIRST_RUN F_2V F_N F_V ITER PCALC VVAP ZETA ZETMAX ZETMIN del
Source Code
VCALC
Variables
Type Visibility Attributes Name Initial
real(kind=8), public :: AT
real(kind=8), public :: AVAP
real(kind=8), public :: DER
real(kind=8), public :: F
logical, public :: FIRST_RUN
real(kind=8), public :: F_2V
real(kind=8), public :: F_N
real(kind=8), public :: F_V
integer, public :: ITER
real(kind=8), public :: PCALC
real(kind=8), public :: VVAP
real(kind=8), public :: ZETA
real(kind=8), public :: ZETMAX
real(kind=8), public :: ZETMIN
real(kind=8), public :: del
Source Code
   recursive subroutine VCALC(ITYP, a, b, del1, T, P, V)
      ! ROUTINE FOR CALCULATION OF VOLUME, GIVEN PRESSURE
      use constants, only: RGAS
      integer, intent(in) :: ITYP ! Type of root desired 1 for liquid -1 for vapor
      real(8), intent(in) :: a
      real(8), intent(in) :: b
      real(8), intent(in) :: del1
      real(8), intent(in) :: T
      real(8), intent(in) :: P
      real(8), intent(out) :: V
      ! Internal variables
      integer :: ITER
      logical :: FIRST_RUN
      real(8) :: ZETMIN, ZETMAX, ZETA, F, F_V, F_2V, F_N, &
                 PCALC, del, AT, DER, VVAP, AVAP
      FIRST_RUN = .TRUE.
      ITER = 0
      ZETMIN = 0.D0
      ZETMAX = .99D0
      if (ITYP .GT. 0) then
         ! Liquid estimate
         ZETA = .5D0
      else
         ! Ideal gas estimate
         ZETA = MIN(.5D0, b*P/(RGAS*T))
      end if
      del = 1.d0
      do while (abs(del) > 1d-10)
         V = b/ZETA
         ITER = ITER + 1
         CALL vdWg_Derivs(a, b, del1, T, V, F, F_V, F_2V, F_N)
         PCALC = RGAS*T*(1/V - F_V)
         if (PCALC .GT. P) then
            ZETMAX = ZETA
         else
            ZETMIN = ZETA
         end if
         AT = F - LOG(V) + V*P/(T*RGAS)
         DER = RGAS*T*(F_2V + 1.d0)/b
         DEL = -(PCALC - P)/DER
         ZETA = ZETA + MAX(MIN(DEL, 0.1d0), -0.1d0)
         if (ZETA .GT. ZETMAX .OR. ZETA .LT. ZETMIN) then
            ZETA = .5D0*(ZETMAX + ZETMIN)
         end if
      end do
      if (ITYP == 0) then
         VVAP = V
         AVAP = AT
         ! Calculate Liquid volume and It's energy
         call VCALC(1, a, b, del1, T, P, V)
         call vdWg_Derivs(a, b, del1, T, V, F, F_V, F_2V, F_N)
         AT = F - LOG(V) + V*P/(T*RGAS)
         if (AT .GT. AVAP) V = VVAP
      end if
   end subroutine VCALC
Call graph
vcalc calls vcalc, vdwg_derivs
vaporpressure calls vcalc, vaporpressure
rkpr_params_from_crit calls vaporpressure