vdWg_Derivs – Multicomponent Equations of State
vdWg_Derivs Subroutine
MIT
28 statements
Source File
public subroutine vdWg_Derivs(a, b, del1, T, V, F, F_V, F_2V, F_N)
Uses
constants
Arguments
Type Intent Optional Attributes Name
real(kind=8), intent(in) :: a
real(kind=8), intent(in) :: b
real(kind=8), intent(in) :: del1
real(kind=8), intent(in) :: T
real(kind=8), intent(in) :: V
real(kind=8), intent(out) :: F
real(kind=8), intent(out) :: F_V
real(kind=8), intent(out) :: F_2V
real(kind=8), intent(out) :: F_N
Called by
Contents
Variables
ATT ATT2V ATTV C ETA REP REP2V REPV SUMC SUMD aRT
Variables
Type Visibility Attributes Name Initial
real(kind=8), public :: ATT
real(kind=8), public :: ATT2V
real(kind=8), public :: ATTV
real(kind=8), public :: C
real(kind=8), public :: ETA
real(kind=8), public :: REP
real(kind=8), public :: REP2V
real(kind=8), public :: REPV
real(kind=8), public :: SUMC
real(kind=8), public :: SUMD
real(kind=8), public :: aRT
Call graph
fug_calc calls vdwg_derivs
vcalc calls vdwg_derivs, vcalc
vaporpressure calls fug_calc, vcalc, vaporpressure
rkpr_params_from_crit calls vaporpressure