VaporPressure – Fortran Program
VaporPressure Subroutine
MIT
47 statements
Source File
public recursive subroutine VaporPressure(a, b, del1, Tc, dc, Tr, PVini, Pv, RHOL, RHOV, phiL)
Uses
constants
Arguments
Type Intent Optional Attributes Name
real(kind=8), intent(in) :: a
real(kind=8), intent(in) :: b
real(kind=8), intent(in) :: del1
real(kind=8), intent(in) :: Tc
real(kind=8), intent(in) :: dc
real(kind=8), intent(in) :: Tr
real(kind=8), intent(in) :: PVini
real(kind=8), intent(out) :: Pv
real(kind=8), intent(out) :: RHOL
real(kind=8), intent(out) :: RHOV
real(kind=8), intent(out) :: phiL
Calls
Called by
Contents
None
Call graph
vaporpressure calls vaporpressure, fug_calc, vcalc
fug_calc calls vdwg_derivs
vcalc calls vcalc, vdwg_derivs
rkpr_params_from_crit calls vaporpressure