name: Docs

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Python
        uses: actions/setup-python@v1 # Use pip to install latest CMake, & FORD/Jin2For, etc.
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: Install ford and make docs
        if: contains( matrix.os, 'ubuntu')
        run: |
          python -m pip install --upgrade pip
          pip install ford
          ford docs.md
     - name: Deploy Documentation for master
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: docs     # The folder the action should deploy.
        clean: true
        clean-exclude: |
          prev
